title: OpenTTD
email: info@openttd.org
description: >- # this means to ignore newlines until "baseurl:"
  An open source simulator based on the classic game Transport Tycoon Deluxe. It attempts to mimic the original game as closely as possible while extending it with new features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock

defaults:
  # set the default template
  - scope:
      path: ""
    values:
      layout: "default"
  # set the template for news collection
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  # set the template for screenshots collection
  - scope:
      path: ""
      type: "screenshots"
    values:
      layout: "screenshot"

collections:
  # Jekyll has built in support for a blog system based on _posts
  # but it's overkill, so I made a simple news collection
  news:
    output: true
  # profiles for post authors, contributors for contact page etc
  people:
    output: false
  # vanilla, this is simply a collection of screenshots with metadata, captions etc
  screenshots:
    output: true
