title: OpenTTD
email: info@openttd.org
description: >- # this means to ignore newlines until "baseurl:"
  An open source simulator based on the classic game Transport Tycoon Deluxe. It attempts to mimic the original game as closely as possible while extending it with new features.
baseurl: ""
url: ""

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "screenshots"
    values:
      layout: "screenshot"

collections:
  posts:
    permalink: /news/:year/:month/:day/:title.html
  people:
    output: false
  screenshots:
    output: true

pagination:
  enabled: true
  collection: "posts"
  per_page: 5
  permalink: "/page/:num/"
  category: "posts"
  sort_field: "date"
  sort_reverse: true
